package io.fourpet.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "usuario")
public class UsuarioEntity {

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;

	@DynamoDBAttribute
	private String nome;

	@DynamoDBAttribute
	private String email;

	@DynamoDBAttribute
	private String senha;

	@DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.BOOL)
	private Boolean anunciante;

}
